services:
  core:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: zeipo-core
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
      - "8084:8084"
      - "5066:5066"
      - "7443:7443"
    runtime: nvidia
    env_file:
      - ../.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '8gb'
    tty: true
    stdin_open: true
    command: sleep infinity
    network_mode: host
    depends_on:
      - freeswitch
      - redis

  freeswitch:
    image: safarov/freeswitch
    container_name: zeipo-freeswitch
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5080:5080"
      - "8021:8021"
      - "8081:8081"
      - "8082:8082"
      - "16384-16484:16384-16484/udp"
    volumes:
      - '../config/freeswitch:/etc/freeswitch'
      - '../config/freeswitch-sounds:/usr/share/freeswitch/sounds'
      - '../logs/freeswitch-logs/freeswitch.log:/var/log/freeswitch/freeswitch.log'
    environment:
      SOUND_RATES: "32000:48000"                                                                                                                                                                                                                                                                                                                                           
      SOUND_TYPES: "en-us-allison"                                                                                                                                                                                                                                                                                                                                         
      EPMD: "false"                                                                                                                                                                                                                                                                                                                                                        
      DUMPCAP: "false"               
    network_mode: host
    restart: unless-stopped

  fail2ban:
    container_name: zeipo-fail2ban
    image: crazymax/fail2ban:latest
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "../config/fail2ban/data:/data"
      - "../logs/freeswitch-logs/freeswitch.log:/var/log/freeswitch/freeswitch.log:ro"
    env_file:
      - "../config/fail2ban/.env"
    restart: always


  redis:
    image: redis:alpine
    container_name: zeipo-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    network_mode: host
    restart: unless-stopped
  

  prometheus:
    image: prom/prometheus:v3.2.1
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - zeipo-network
    
  grafana:
    image: grafana/grafana:11.6.0
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - zeipo-network
    env_file:
      - ./.env
    depends_on:
      - prometheus
      
  timescaledb:
    image: timescale/timescaledb:2.19.0-pg14
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./config/timescaledb/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - zeipo-network
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  timescale_data:

networks:
  zeipo-network:
    driver: bridge